
--                                BASIC SQL QUERIES

create database sql_practice;
use sql_practice;

create table grade(
ID INTEGER,
Major VARCHAR(100),
GPA DECIMAL(10,1)
);

SHOW VARIABLES LIKE 'secure_file_priv';

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/SQL_PRACTICE1/program.csv'
INTO TABLE grade
FIELDS TERMINATED BY ','
LINES terminated by '\n'
IGNORE 1 ROWS;

SELECT * FROM GRADE;
SELECT MAJOR FROM GRADE;
SELECT ID,GPA FROM GRADE;

SELECT MAJOR,GPA FROM GRADE WHERE GPA>=3.5;

SELECT * FROM GRADE WHERE GPA>=3.2 AND GPA<=3.6;

SELECT AVG(GPA) FROM GRADE;

SELECT MAJOR, count(*) FROM GRADE group by MAJOR;

--                                 SORTING AND FILTERING

SELECT * FROM GRADE;

SELECT * FROM GRADE ORDER BY MAJOR;

SELECT * FROM GRADE ORDER BY MAJOR DESC;

SELECT * FROM GRADE WHERE GPA > 3.6;

SELECT MAJOR,GPA FROM GRADE WHERE GPA BETWEEN 3.4 AND 3.7 order by GPA DESC;

-- FILTERING STUDENT SELECTING CS OR MATHS
SELECT * FROM GRADE WHERE MAJOR IN('COMPUTER SCIENCE','MATH');

-- SORTING IN MAJOR COLUMN IN ASC ORDER AND GPA COLUMN IN DESC ORDER
SELECT * FROM GRADE ORDER BY MAJOR, GPA DESC;

-- RETURN ID, MAJOR COLUMNS FOR STUDENTS WITH GPA > AVG GPA
SELECT ID, MAJOR FROM GRADE WHERE GPA > (SELECT avg(GPA) FROM GRADE);

-- RETURN TOP 3 MAJORS WITH THE HIGHEST AVG GPA ALONG WITH THEIR AVG GPAS
SELECT MAJOR,AVG(GPA) AS AVGPA FROM GRADE group by MAJOR order by AVGPA DESC LIMIT 3 ;

SELECT * FROM GRADE 
WHERE MAJOR IN('COMPUTER SCIENCE','MATH') AND GPA>3.5 
order by GPA DESC;

--                       AGGREGATING DATA


SELECT sum(GPA) FROM GRADE;
SELECT AVG(GPA) FROM GRADE;
SELECT COUNT(ID) FROM GRADE;
SELECT MIN(GPA) FROM GRADE;
SELECT MAX(GPA) FROM GRADE;


-- SUM OF GPAS FOR STUDENT MAJORING IN CS
SELECT sum(GPA) FROM GRADE WHERE MAJOR='COMPUTER SCIENCE';

-- COUNT OF STUDENT MAJORING IN BUSINESS
SELECT COUNT(ID) FROM GRADE WHERE MAJOR='BUSINESS';

-- AVG GPAS FOR STUDENT MAJORING IN MATH
SELECT AVG(GPA) FROM GRADE WHERE MAJOR='MATH';

-- MIN AND MAX GPAS FOR STUDENT MAJORING IN HISTORY
SELECT MIN(GPA),MAX(GPA) FROM GRADE WHERE MAJOR='HISTORY';

-- SUM OF GPAS FOR EACH MAJOR, SORTED IN DESC ORDER OF THE SUM 
SELECT MAJOR, SUM(GPA) AS SUM_GPA FROM GRADE GROUP BY MAJOR ORDER BY SUM_GPA DESC;

-- FIND THE MAJOR WITH THE HEIGHEST AVG GPA
SELECT MAJOR, AVG(GPA) FROM GRADE
group by MAJOR 
HAVING AVG(GPA)= (SELECT MAX(AVGGPA) FROM (SELECT AVG(GPA) AS AVGGPA FROM GRADE GROUP BY MAJOR) AS T);

SELECT MAJOR, AVG(GPA) FROM GRADE
group by MAJOR 
ORDER BY AVG(GPA) DESC
LIMIT 1;

--                                 joins

create table courses(
ID INTEGER,
Course VARCHAR(100)
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/SQL_PRACTICE1/Courses.csv'
INTO TABLE Courses
FIELDS TERMINATED BY ','
LINES terminated by '\n'
IGNORE 1 ROWS;

select * FROM COURSES;

-- WHAT ARE THE COURSES TAKEN BY STUDENTS MAJORING IN CS?
SELECT G.ID,C.COURSE FROM GRADE G INNER JOIN COURSES C ON G.ID=C.ID WHERE G.MAJOR='COMPUTER SCIENCE';

-- LIST OF ALL STUDENTS AND THE COURSES THEY' VE TAKEN INCLUDING THOSE WHP HAVENT TAKEN ANY
SELECT G.ID, C.COURSE FROM GRADE G LEFT JOIN COURSES C ON G.ID=C.ID;

-- ARE THERE ANY STUDENTS WHO HAVE TAKEN MORE THAN ONE COURSE
SELECT C.ID, COUNT(C.COURSE) FROM COURSES C group by C.ID
having COUNT(C.COURSE)>1;

-- COMBINE TWO TABLE AND GET BOTH TABLE DATA 
select G.*,C.* FROM GRADE G LEFT JOIN COURSES C ON G.ID=C.ID
UNION
select G.*,C.* FROM GRADE G RIGHT JOIN COURSES C ON G.ID=C.ID;

-- CROSS JOIN
SELECT G.ID, C.COURSE FROM GRADE G CROSS JOIN COURSES C;

-- WHICH STUDENTS HAVE A GPA>3.5 AND TAKING THE COURSE BUS101
SELECT C.COURSE FROM GRADE G INNER JOIN COURSES C ON G.ID=C.ID WHERE G.GPA>3.5 AND  C.COURSE LIKE '%BUS%';

-- FOR EACH COURSE
SELECT C.COURSE,G.ID FROM GRADE G RIGHT JOIN COURSES C ON G.ID=C.ID;

-- AVG GPA
SELECT AVG(G.GPA) FROM GRADE G JOIN COURSES C ON G.ID=C.ID WHERE C.COURSE LIKE '%CS%';


--                                    subqueries 